# Generated by Django 5.2.6 on 2025-10-08 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_created_date_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_choices',
            field=models.CharField(choices=[('tech', 'Technology & innovation'), ('fashion', 'design & fashion'), ('food', 'food & cooking'), ('creativity', 'creative corner'), ('myspace', 'personal gist'), ('inpiration', 'inspirational boards'), ('other', 'others')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
