# Generated by Django 5.2.6 on 2025-10-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_category_choices_post_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_choices',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(),
        ),
    ]
