# Generated by Django 5.2.6 on 2025-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_text_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology & innovation'), ('fashion', 'design & fashion'), ('food', 'food & cooking'), ('creativity', 'creative corner'), ('inpiration', 'inspirational boards'), ('myspace', 'personal gist'), ('other', 'others')], default='other', max_length=20),
        ),
    ]
